spring.application.name=lostAndFound
spring.datasource.url=jdbc:postgresql://localhost:5432/lost_and_found
spring.datasource.username=postgres
spring.datasource.password=Jolidon21
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


upload.directory=/home/ortniel/Personal_Work/Retrivio/uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
